---
x-db-environment: &x-db-environment
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "taskL0DB"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  POSTGRES_SSL_MODE: "disable"

x-kafka-environment: &x-kafka-environment
  KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
  KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "order-topic:1:1"

services:
  app:
    container_name: app
    image: l0:v0.1
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db
      - kafka
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    ports:
      - "5432:5432"
    networks:
      - app_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
        - "2181:2181"
    networks:
      - app_network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
        - "9092:9092"
    links:
        - zookeeper
    environment:
      <<: *x-kafka-environment
    depends_on:
        - zookeeper
    networks:
      - app_network


networks:
  app_network:
    external: false

...
